# Generated by Django 4.2.7 on 2023-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatmug_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('canceled', 'canceled')], help_text='Current status of the PO.', max_length=10),
        ),
    ]
